version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAG: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:cached
    networks:
      - app-network

  #Nginx service
  webserver:
    depends_on:
      - app
      - db
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8088:80"
      - "443:443"
    volumes:
      - ./:/var/www:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/:cached
      #- /home/user-data/ssl/:/etc/nginx/conf.d/:delegated
    networks:
      - app-network

  #MYSQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASENAME}
      MYSQL_USER: ${DK_DB_USER}
      MYSQL_PASSWORD: ${DK_DB_PSW}
      MYSQL_ROOT_PASSWORD: ${DK_DB_PSW}
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql:cached
      - ./mysql/my.cnf:/etc/mysql/my.cnf:cached
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

